### ISSUE TITLE
Usage in README.md confuses networks

### ISSUE THREAD

**Issue by frankbraun** [near/near-eth-rpc#10]
The [usage](https://github.com/near/near-eth-rpc#usage) section in the README.md confuses networks. When working through the setup that threw me off.

- It asks to create a wallet on **betanet** via https://wallet.betanet.near.org
- Then `near login` defaults to **testnet**
- Then the user is supposed to run `NEAR_MASTER_ACCOUNT=you.betanet npm run start` which runs on **betanet**.

If I follow the outline I don't have an account on **testnet** to log into.

The obvious fix for me was to use `env NEAR_ENV=betanet near login`, but that seems to be broken due to https://github.com/near/near-wallet/issues/1510

So I created an account on **testnet**, logged into it, and ran `near-eth-rpc` on **betanet**. That seems to work, but is kind of confusing.

**Comment by artob** [comment]
Thanks!
